### ISSUE TITLE
Toast message missing upon product scan.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/receiving#309]
## Current behavior
Toast message missing upon successful product scan.

## Expected behavior
Toast message should be '<Internal Name>' scanned successfully' can be displayed on successful product scan.

## Environment details
- App version : 2.22.0 
- Environment: UAT

**Comment by ymaheshwari1** [comment]
@Adameddy26 I think instead of showing toast on successful scan, we can show a toast when the scanning fails/product is not found, as on success we update the qty of the product so there is no such use case of showing a toast.

Also there is an issue already created for showing a toast when scanning fails
https://github.com/hotwax/receiving/issues/308

**Comment by Adameddy26** [comment]
Hi @ymaheshwari1 
Toast message should be generated for successful product scan. It will add value to user experience. 
FYI: Discussed this internally in the team.
